import { randomUUID } from "node:crypto";
import { backendArtifactSchema, type BackendArtifact, type MarketResearch, type WebsiteArtifact } from "@launchforge/shared";

export interface BackendAgentInput {
  projectId: string;
  idea: string;
  marketResearch?: MarketResearch;
  websiteArtifact?: WebsiteArtifact;
}

export interface BackendAgent {
  plan(input: BackendAgentInput): Promise<BackendArtifact>;
}

export function createBackendAgent(): BackendAgent {
  return {
    async plan(input) {
      const now = new Date().toISOString();
      const productName = input.websiteArtifact?.productName ?? input.marketResearch?.brand.name ?? deriveProductName(input.idea);
      const tableName = `${normalizeIdentifier(productName)}_waitlist_leads`;
      const endpointName = `create_${normalizeIdentifier(productName)}_waitlist_lead`;

      return backendArtifactSchema.parse({
        id: randomUUID(),
        projectId: input.projectId,
        productName,
        mode: "planned",
        tables: [
          {
            name: tableName,
            description: `Stores waitlist leads for ${productName}.`,
            fields: [
              { name: "id", type: "int", required: true, description: "Primary key generated by Xano." },
              { name: "email", type: "email", required: true, description: "Visitor email address." },
              { name: "source", type: "text", required: false, description: "Lead source or campaign marker." },
              { name: "product_name", type: "text", required: true, description: "Product that received the signup." },
              { name: "metadata", type: "json", required: false, description: "Non-sensitive launch metadata." },
              { name: "created_at", type: "timestamp", required: true, description: "Signup creation timestamp." }
            ]
          }
        ],
        endpoints: [
          {
            name: endpointName,
            verb: "POST",
            path: "/waitlist",
            tableName,
            description: `Accepts a public waitlist signup for ${productName}.`,
            xanoScript: buildWaitlistEndpointScript(endpointName, tableName, productName)
          }
        ],
        frontendConnection: {
          environmentVariable: "VITE_PRODUCT_API_URL",
          clientFilePath: "src/productApi.ts",
          usage: "POST /waitlist with { email, source, productName } from the generated product website."
        },
        generatedAt: now,
        updatedAt: now
      });
    }
  };
}

export function buildWaitlistEndpointScript(endpointName: string, tableName: string, productName: string): string {
  return `query ${normalizeIdentifier(endpointName)} verb=POST {
  input {
    email email
    text? source
    json? metadata
  }
  stack {
    db.add ${normalizeIdentifier(tableName)} {
      data = {
        email: $input.email,
        source: $input.source,
        product_name: "${escapeXanoString(productName)}",
        metadata: $input.metadata
      }
    } as $lead
  }
  response = {
    ok: true,
    id: $lead.id
  }
}`;
}

function deriveProductName(idea: string): string {
  const seed =
    idea
      .replace(/[^a-zA-Z0-9 ]/g, " ")
      .split(/\s+/)
      .find((word) => word.length > 3 && !["launch", "with", "that", "platform", "startup"].includes(word.toLowerCase())) ??
    "Launch";

  return `${seed.charAt(0).toUpperCase()}${seed.slice(1).toLowerCase()}`;
}

function normalizeIdentifier(value: string): string {
  const normalized = value
    .toLowerCase()
    .replace(/[^a-z0-9_ ]/g, "")
    .trim()
    .replace(/\s+/g, "_")
    .replace(/^_+|_+$/g, "");

  return normalized || "launchforge";
}

function escapeXanoString(value: string): string {
  return value.replaceAll("\\", "\\\\").replaceAll('"', '\\"').replaceAll("\n", " ");
}
